---
- name: "Cron | Insert ENV variables"
  ansible.builtin.cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    env: true
    user: "{{ sharedlists_user }}"
  loop:
    - name: RAILS_ENV
      job: production
    - name: SECRET_KEY_BASE
      job: "{{ sharedlists_secret_key_base }}"

- name: "Cron | Install job"
  ansible.builtin.cron:
    name: Update suppliers
    user: "{{ sharedlists_user }}"
    minute: "14"
    hour: "11,16,20"
    job: /bin/bash -lc "cd {{ sharedlists_home }} && rbenv exec rails sync_ftp_files --silent > /dev/null"
