---
- name: "Monitoring | Copy Monit file"
  ansible.builtin.template:
    src: monit.j2
    dest: /etc/monit/conf-enabled/sharedlists
    mode: "0644"
  when: "'monit' in ansible_facts.packages"
  notify: reload monit

- name: "Monitoring | Download Munin plugin"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/munin-monitoring/contrib/master/plugins/puma/puma_
    dest: /usr/local/bin/puma_
    mode: "0755"
  when: "'munin-node' in ansible_facts.packages"

- name: "Monitoring | Enable Munin plugin"
  ansible.builtin.file:
    src: /usr/local/bin/puma_
    dest: "/etc/munin/plugins/puma_{{ item }}"
    state: link
  loop:
    - average
    - memory
  when: "'munin-node' in ansible_facts.packages"
  notify: restart munin-node
