---
- name: "Sharedlists | Configure git safe.directory"
  ansible.builtin.command:
    cmd: " git config --global --add safe.directory {{ sharedlists_home }}"

- name: "Sharedlists | Clone repository"
  ansible.builtin.git:
    repo: "{{ sharedlists_git_url }}"
    dest: "{{ sharedlists_home }}"
    version: "{{ sharedlists_git_branch }}"
    force: true

- name: "Sharedlists | Ruby version lookup"
  ansible.builtin.shell: cat "{{ sharedlists_home }}/.ruby-version"
  register: ruby_version
  changed_when: false

- name: "Sharedlists | Change directory owner"
  ansible.builtin.file:
    path: "{{ sharedlists_home }}"
    state: directory
    recurse: true
    owner: "{{ sharedlists_user }}"
    group: "{{ sharedlists_user }}"

- name: "Sharedlists | Setup rbenv"
  ansible.builtin.lineinfile:
    path: "{{ sharedlists_user_home }}/.bashrc"
    line: eval "$(rbenv init -)"

- name: "Sharedlists | Create rbenv plugin directory"
  ansible.builtin.file:
    path: "{{ ruby_path }}/plugins"
    state: directory
    owner: "{{ sharedlists_user }}"
    group: "{{ sharedlists_user }}"

- name: "Sharedlists | Install ruby-build"
  ansible.builtin.git:
    repo: "{{ ruby_build_git_url }}"
    dest: "{{ ruby_path }}/plugins/ruby-build"
    version: master

- name: "Sharedlists | Install ruby"
  ansible.builtin.command:
    cmd: 'rbenv install {{ ruby_version.stdout }}'
    creates: "{{ ruby_path }}/versions/{{ ruby_version.stdout }}/bin/ruby"
  become: true
  become_user: "{{ sharedlists_user }}"

- name: "Sharedlists | Install bundler"
  ansible.builtin.command:
    cmd: rbenv exec gem install bundler
    chdir: "{{ sharedlists_home }}"
    creates: "{{ ruby_path }}/versions/{{ ruby_version.stdout }}/bin/bundler"
  become: true
  become_user: "{{ sharedlists_user }}"

# https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries
- name: "Sharedlists | Configure nokogiri"
  ansible.builtin.command:
    cmd: 'rbenv exec bundle config build.nokogiri "--use-system-libraries"'
    chdir: "{{ sharedlists_home }}"
  become: true
  become_user: "{{ sharedlists_user }}"
  environment:
    RAILS_ENV: production

- name: "Sharedlists | Set bundle options"
  ansible.builtin.command:
    cmd: "rbenv exec bundle config set --local without 'development test'"
    chdir: "{{ sharedlists_home }}"
    creates: "{{ sharedlists_home }}/.bundle/config"
  become: true
  become_user: "{{ sharedlists_user }}"

- name: "Sharedlists | Install ruby packages"
  ansible.builtin.command:
    cmd: "rbenv exec bundle install"
    chdir: "{{ sharedlists_home }}"
  become: true
  become_user: "{{ sharedlists_user }}"
  environment:
    RAILS_ENV: production

- name: "Sharedlists | Create suppliers directory"
  ansible.builtin.file:
    path: "{{ sharedlists_home }}/supplier_assets"
    state: directory
    owner: "{{ sharedlists_user }}"
    group: "{{ sharedlists_user }}"
    mode: "0755"

- name: "Sharedlists | Add logrotate configuration"
  ansible.builtin.template:
    src: logrotate.d/sharedlists.j2
    dest: /etc/logrotate.d/sharedlists
    mode: "0644"
